// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore: unused_import
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSY2Ij9szTenJKwyKfKNKpT3oxKTF35R0',
    appId: '1:159377229826:web:1bb74e3a4c1fa3bd67ff1b',
    messagingSenderId: '159377229826',
    projectId: 'pks-shop-8e3b4',
    authDomain: 'pks-shop-8e3b4.firebaseapp.com',
    storageBucket: 'pks-shop-8e3b4.firebasestorage.app',
    measurementId: 'G-DGWRL2KS91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7lr_Qzkj3WCq8Gpouvb57Ip7THuDYlos',
    appId: '1:159377229826:android:e8f09fd9ea92736567ff1b',
    messagingSenderId: '159377229826',
    projectId: 'pks-shop-8e3b4',
    storageBucket: 'pks-shop-8e3b4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSY2Ij9szTenJKwyKfKNKpT3oxKTF35R0',
    appId: '1:159377229826:web:acd7c6ace972a1bb67ff1b',
    messagingSenderId: '159377229826',
    projectId: 'pks-shop-8e3b4',
    authDomain: 'pks-shop-8e3b4.firebaseapp.com',
    storageBucket: 'pks-shop-8e3b4.firebasestorage.app',
    measurementId: 'G-X6LFTL2RGT',
  );
}

